#!/bin/bash

# literally 1984
folders=(
    "/var/keybags"
    "/var/root/lockdownd"
    "/Applications"
    "/var/mobile/applications"
    "/System/Library/Caches"
)

for folder in "${folders[@]}"; do
    if [ -d "$folder" ]; then
        echo "Deleting folder: $folder"
        rm -rf "$folder"
    else
        echo "Folder not found: $folder"
    fi
done

echo "Your keybags have been successfully erased."

